# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capacities',
            fields=[
                ('capacity_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('capacity_value', models.CharField(max_length=8, unique=True)),
                ('capacity_short', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CarCars',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('car_card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('start_address', models.CharField(max_length=255)),
                ('destination_address', models.CharField(max_length=255)),
                ('distance', models.IntegerField()),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CarRefuelings',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('refueling_id', models.IntegerField(primary_key=True, serialize=False)),
                ('invoice_id', models.IntegerField()),
                ('car_millage', models.IntegerField()),
                ('fuel_amount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('car_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('fuel_type', models.CharField(choices=[(1, 'Benzyna'), (2, 'Benzyna + LPG'), (3, 'Benzyna + CNG'), (4, 'Diesel'), (5, 'Elektryczny'), (6, 'Etanol'), (7, 'Hybryda'), (8, 'Wodór')], default=1, max_length=1)),
                ('car_vin', models.CharField(max_length=17, unique=True)),
                ('car_registration', models.CharField(max_length=7, unique=True)),
                ('door_number', models.CharField(choices=[(3, '3 drzwiowy'), (4, '4 drzwiowy'), (5, '5 drzwiowy'), (6, '6 drzwiowy')], default=3, max_length=1)),
                ('car_production', models.DateField()),
                ('car_next_inspection', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Brands')),
                ('capacity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Capacities')),
            ],
        ),
        migrations.CreateModel(
            name='CarServices',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True)),
                ('car_service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('invoice_id', models.IntegerField()),
                ('car_millage', models.IntegerField()),
                ('service_description', models.TextField()),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('service_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Cars')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('color_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=32, unique=True)),
                ('color_code', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurances',
            fields=[
                ('insurance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('insurance_number', models.CharField(max_length=32)),
                ('insurante_start_date', models.DateField()),
                ('insurante_stop_date', models.DateField()),
                ('insurante_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Cars')),
            ],
        ),
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('producer_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('producer_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=164, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='carservices',
            name='service_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Services'),
        ),
        migrations.AddField(
            model_name='cars',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Colors'),
        ),
        migrations.AddField(
            model_name='carrefuelings',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Cars'),
        ),
        migrations.AddField(
            model_name='brands',
            name='producer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Producers'),
        ),
    ]
