# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brand_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='brands',
            name='brand_name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='capacities',
            name='capacity_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='capacities',
            name='capacity_value',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='carcars',
            name='car_card_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carcars',
            name='distance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carrefuelings',
            name='car_millage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carrefuelings',
            name='invoice_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carrefuelings',
            name='refueling_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carservices',
            name='car_millage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carservices',
            name='car_service_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carservices',
            name='invoice_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carservices',
            name='service_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='colors',
            name='color_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='insurances',
            name='insurance_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producers',
            name='producer_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
