# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20170406_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacities',
            name='capacity_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colors',
            name='color_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
